# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    connection-timeout: 5000ms
    servlet: 
      context-path: /zwf

spring:
    # 环境 dev|uat|prd
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    mvc:
        throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**
    resources:
#        add-mappings: false    
        static-locations: classpath:/static/,classpath:/views/ 
    servlet: 
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
#mybatis
mybatis-plus:
  mapper-locations:
   - classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zwf.modules.*.entity
  global-config: 
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
     #驼峰下划线转换
    db-column-underline: true
  
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true    
    
logging:
    #path: E:\zwf\base-boot
    file: logs\base-boot.log
    level:
      root: info 
      com.zwf: debug
